// AdvisorTiles — the 12 tiles composing the Advisor Dashboard.
// Each tile: Card with header (title + overflow), body, and footer (As of Today / See more).
// All in a single file to keep the shell tight.

/* Period context — set by the dashboard secondary-menu filter at App level.
   Tiles consume this to render period-appropriate data + footer labels. */
const PeriodContext = React.createContext('Year to date');
window.PeriodContext = PeriodContext;

function periodToLabel(period) {
  switch (period) {
    case 'Today':           return 'Today · May 13';
    case 'This week':       return 'May 7 – 13';
    case 'This month':      return 'May 1 – 13';
    case 'This quarter':    return 'Apr – May';
    case 'Year to date':    return 'Jan – May';
    case 'Last 12 months':  return 'Jun \u201925 – May \u201926';
    case 'All time':        return 'All time';
    default:                return period || 'As of Today';
  }
}
window.periodToLabel = periodToLabel;

const TILE = {
  background: 'rgba(255,255,255,0.05)',
  border: '1px solid rgb(75,85,99)',
  borderRadius: 14,
  display: 'flex', flexDirection: 'column',
  color: 'rgb(249,250,251)',
  overflow: 'hidden',
  height: '100%',
  minHeight: 'var(--tile-min-height, 440px)',
};
const TILE_HEAD = { display:'flex', alignItems:'center', padding:'14px 16px 10px' };
const TILE_TITLE = { fontFamily:'Inter', fontWeight:600, fontSize:15, letterSpacing:'-0.01em' };
const TILE_BODY = { flex:1, padding:'0 16px 8px', display:'flex', flexDirection:'column', minHeight:0 };
const TILE_FOOT = {
  display:'flex', alignItems:'center', justifyContent:'space-between',
  padding:'10px 16px', borderTop:'1px solid rgba(75,85,99,0.55)',
  fontFamily:'Inter', fontSize:12, color:'rgb(163,163,163)',
};
const SEE_MORE = {
  display:'inline-flex', alignItems:'center', gap:4,
  color:'rgb(5,122,85)', textDecoration:'none', fontSize:12, fontWeight:500, cursor:'pointer',
};
const OVERFLOW = {
  background:'transparent', border:'none', color:'rgb(163,163,163)', cursor:'pointer',
  width:24, height:24, borderRadius:6, display:'inline-flex', alignItems:'center', justifyContent:'center',
};

/* Per-tile data provenance — surfaced via the info icon in each tile header.
   Keyed by tile title. `source` = where the data originates; `method` = how
   the numbers are derived; `cadence` = refresh frequency. */
const TILE_INFO = {
  'Upcoming Meetings': {
    source: 'Synced from your connected calendar (Google / Outlook) and the CRM meeting log.',
    cadence: 'Refreshes every 15 minutes',
  },
  'Notifications': {
    source: 'Aggregated from CRM tasks, custodian alerts (Schwab / Fidelity), e-signature status, and the AI monitoring engine.',
    cadence: 'Real-time',
  },
  'Opportunities': {
    source: 'Generated by the overnight AI analysis run across all household portfolios and held-away accounts.',
    method: 'Each portfolio is scored for drift, tax-loss harvesting, idle cash, and concentration against the household’s target policy. Dollar values reflect the assets in scope for the action.',
    cadence: 'Recomputed nightly at 2:00 AM ET',
  },
  'Top Clients': {
    source: 'Household-level balances from the custodian feed and your book-of-business records.',
    cadence: 'Updated daily after custodian reconciliation',
  },
  'Billing Summary': {
    source: 'Your fee schedule plus reconciled period-end account balances.',
    method: 'Fees = billable AUM × applied advisory rate, prorated for the period. Collected vs. outstanding is reconciled against custodian debits and the AR ledger.',
    cadence: 'Updated daily; finalized at quarter close',
  },
  'Content Hub': {
    source: 'Engagement events from the client portal and email campaign tool.',
    method: 'Shows the most recent shares and opens across your client base. Activity reflects unique client interactions, de-duplicated per 24 hours.',
    cadence: 'Refreshes hourly',
  },
  'AUM Asset Allocation': {
    source: 'Position-level holdings from custodians, classified by the security master.',
    method: 'Each holding is mapped to an asset class and aggregated by market value across all managed accounts, then expressed as a percent of total AUM.',
    cadence: 'Updated daily after market close',
  },
  'Assets Under Management': {
    source: 'Reconciled account balances from the custodian feed, grouped by account registration type.',
    method: 'Total managed market value as of the prior business close. “Held-away” reflects accounts you advise on but do not custody.',
    cadence: 'Updated daily after custodian reconciliation',
  },
  'Cash Flow': {
    source: 'Transaction records from the custodian feed (contributions, distributions, fees, transfers).',
    method: 'Net flow = inflows − outflows for the selected period, excluding internal transfers between a household’s own accounts.',
    cadence: 'Updated daily',
  },
  'Projected Fees': {
    source: 'Current billable AUM, your fee schedule, and a forward growth assumption.',
    method: 'Projects advisory revenue through 2030 using a blended portfolio growth rate plus modeled net new assets. A planning estimate — not a guarantee of future revenue.',
    cadence: 'Recomputed weekly',
  },
  'Holdings Breakdown': {
    source: 'Position-level holdings from custodians, rolled up across all managed accounts.',
    method: 'Top 10 securities ranked by aggregate market value (AUM). Identical tickers are combined across accounts and households.',
    cadence: 'Updated daily after market close',
  },
  'Client Activity': {
    source: 'Touchpoint log from the CRM — meetings, calls, emails, and portal logins.',
    method: 'Each cell is one client-week; intensity reflects the count of logged interactions over the last 26 weeks.',
    cadence: 'Refreshes daily',
  },

  /* --- My Practice --- */
  'Client Age': {
    source: 'Client birthdates from CRM profiles, joined to reconciled custodian balances.',
    method: 'Households are bucketed into age brackets; bars compare aggregate AUM to total client assets (including held-away) per bracket.',
    cadence: 'Updated daily',
  },
  'Open Date': {
    source: 'Account open dates from the custodian feed and CRM relationship records.',
    method: 'Clients are grouped by tenure (years since their first account opened); AUM vs. total assets shown per tenure band.',
    cadence: 'Updated daily',
  },
  'Client Age Distribution': {
    source: 'Client birthdates from CRM profiles.',
    method: 'Headcount per age band, with each band expressed as a percent of your total book.',
    cadence: 'Updated daily',
  },
  'Client Occupation': {
    source: 'Occupation field on CRM client profiles.',
    method: 'Clients and their aggregate AUM grouped by occupation category. Uncategorized profiles are excluded.',
    cadence: 'Updated daily',
  },
  'AUM Tier Distribution': {
    source: 'Reconciled household balances from the custodian feed.',
    method: 'Households are grouped into AUM tiers; each row shows the client count and total AUM in that tier.',
    cadence: 'Updated daily after custodian reconciliation',
  },
  'Service Penetration': {
    source: 'Service enrollment and engagement records from the CRM.',
    method: 'Share of clients enrolled in each service line (investment, planning, tax, estate). A client can count toward more than one service.',
    cadence: 'Updated daily',
  },
  'Top Asset Managers': {
    source: 'Position-level holdings classified by fund family / asset manager via the security master.',
    method: 'Aggregate AUM grouped by asset manager across all managed accounts, ranked by market value.',
    cadence: 'Updated daily after market close',
  },
  'Managed Assets Growth': {
    source: 'Reconciled period-end account balances from the custodian feed.',
    method: 'Trend of total managed AUM over time. Growth reflects both market movement and net new assets.',
    cadence: 'Updated daily',
  },
  'Positions': {
    source: 'Position-level holdings from the custodian feed.',
    method: 'Holdings rolled up across all managed accounts, showing market value and portfolio weight per security.',
    cadence: 'Updated daily after market close',
  },
  'Inflows & Outflows': {
    source: 'Transaction records from the custodian feed.',
    method: 'Inflows (contributions, transfers in) vs. outflows (distributions, fees, transfers out) per period, excluding internal transfers between a household’s own accounts.',
    cadence: 'Updated daily',
  },
  'Cash Flow by Type': {
    source: 'Custodian transactions classified by transaction type.',
    cadence: 'Updated daily',
  },
  'Net Cash Flow Trend': {
    source: 'Custodian transaction feed.',
    method: 'Net flow (inflows − outflows) charted over time, excluding internal transfers.',
    cadence: 'Updated daily',
  },
  'Cash Flow by Account Type': {
    source: 'Custodian transactions joined to account registration type.',
    method: 'Net flow grouped by account type (taxable, IRA, Roth, trust, etc.) for the selected period.',
    cadence: 'Updated daily',
  },
  'Recent Transactions': {
    source: 'Posted transactions from the custodian feed.',
    cadence: 'Refreshes hourly',
  },

  /* --- My Practice KPIs --- */
  'Total AUM': {
    source: 'Reconciled account balances from the custodian feed.',
    method: 'Sum of market value across all managed accounts as of the prior business close.',
    cadence: 'Updated daily after custodian reconciliation',
  },
  'YTD Growth': {
    source: 'Reconciled period-end balances from the custodian feed.',
    method: 'Dollar change in managed AUM since January 1, net of contributions and withdrawals.',
    cadence: 'Updated daily',
  },
  'Accounts': {
    source: 'Account registry from the custodian feed and CRM.',
    method: 'Count of active managed accounts. Closed and held-away accounts are excluded.',
    cadence: 'Updated daily',
  },
  'YTD Fees': {
    source: 'Advisory fee billing ledger.',
    method: 'Total advisory fees billed year-to-date across all households.',
    cadence: 'Updated daily; finalized at quarter close',
  },
  'Total Inflows': {
    source: 'Custodian transaction feed.',
    method: 'Sum of contributions and transfers in for the period, excluding internal transfers between a household’s own accounts.',
    cadence: 'Updated daily',
  },
  'Total Outflows': {
    source: 'Custodian transaction feed.',
    method: 'Sum of distributions, fees, and transfers out for the period, excluding internal transfers.',
    cadence: 'Updated daily',
  },
  'Net Cash Flow': {
    source: 'Custodian transaction feed.',
    method: 'Total inflows minus total outflows for the period, excluding internal transfers.',
    cadence: 'Updated daily',
  },
  'Total Transactions': {
    source: 'Custodian transaction feed.',
    method: 'Count of posted transactions across all managed accounts for the period. Pending trades are excluded.',
    cadence: 'Refreshes hourly',
  },
};

function TileInfo({ title }) {
  const info = TILE_INFO[title];
  const [open, setOpen] = React.useState(false);
  const [pos, setPos] = React.useState({ top:0, left:0 });
  const wrapRef = React.useRef();
  const btnRef = React.useRef();
  const POP_W = 300;
  const place = React.useCallback(() => {
    const el = btnRef.current;
    if (!el) return;
    const r = el.getBoundingClientRect();
    const margin = 12;
    let left = r.left - 6;
    left = Math.min(left, window.innerWidth - POP_W - margin);
    left = Math.max(margin, left);
    setPos({ top: r.bottom + 8, left, arrow: r.left + r.width/2 - left });
  }, []);
  React.useEffect(() => {
    if (!open) return;
    place();
    const onDoc = (e) => { if (wrapRef.current && !wrapRef.current.contains(e.target)) setOpen(false); };
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    const onReflow = () => place();
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    window.addEventListener('resize', onReflow);
    window.addEventListener('scroll', onReflow, true);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      document.removeEventListener('keydown', onKey);
      window.removeEventListener('resize', onReflow);
      window.removeEventListener('scroll', onReflow, true);
    };
  }, [open, place]);
  if (!info) return null;
  const Row = ({ icon, label, text, color }) => (
    <div style={{ display:'flex', gap:10, padding:'10px 0', borderTop:'1px solid rgba(75,85,99,0.4)' }}>
      <span style={{ flex:'0 0 auto', width:22, height:22, borderRadius:6, background:'rgba(255,255,255,0.05)', display:'inline-flex', alignItems:'center', justifyContent:'center', color }}>
        <i className={`fa-solid ${icon}`} style={{ width:12, height:12 }} />
      </span>
      <div style={{ minWidth:0 }}>
        <div style={{ fontFamily:'Inter', fontSize:10.5, fontWeight:600, letterSpacing:0.5, textTransform:'uppercase', color:'rgb(140,140,140)', marginBottom:3 }}>{label}</div>
        <div style={{ fontFamily:'Inter', fontSize:12.5, lineHeight:1.5, color:'rgb(209,213,219)' }}>{text}</div>
      </div>
    </div>
  );
  return (
    <span ref={wrapRef} style={{ display:'inline-flex', marginLeft:7 }} onMouseDown={(e)=>e.stopPropagation()}>
      <button
        ref={btnRef}
        className="tile-info-btn"
        aria-label={`How “${title}” is calculated`}
        aria-haspopup="dialog"
        aria-expanded={open}
        onClick={(e)=>{ e.stopPropagation(); setOpen(o=>!o); }}
        style={{
          background:'transparent', border:'none', cursor:'pointer', padding:0,
          width:18, height:18, borderRadius:9, display:'inline-flex', alignItems:'center', justifyContent:'center',
          color: open ? 'rgb(94,214,164)' : 'rgb(120,124,130)', transition:'color 120ms ease',
        }}
      >
        <i className="fa-solid fa-circle-info" style={{ width:14, height:14 }} />
      </button>
      {open && ReactDOM.createPortal((
        <div role="dialog" aria-label={`${title} — data source`} onMouseDown={(e)=>e.stopPropagation()} style={{
          position:'fixed', top:pos.top, left:pos.left, zIndex:9000, width:POP_W, boxSizing:'border-box',
          background:'rgb(28,30,34)', border:'1px solid rgb(75,85,99)', borderRadius:12,
          boxShadow:'0 16px 40px -8px rgba(0,0,0,0.6)', padding:'12px 14px 4px', cursor:'default',
        }}>
          <div style={{
            position:'absolute', top:-6, left:Math.max(8, Math.min((pos.arrow||14)-5, POP_W-18)), width:10, height:10, background:'rgb(28,30,34)',
            borderLeft:'1px solid rgb(75,85,99)', borderTop:'1px solid rgb(75,85,99)', transform:'rotate(45deg)',
          }} />
          <div style={{ fontFamily:'Inter', fontSize:13, fontWeight:600, color:'rgb(249,250,251)', paddingBottom:8 }}>{title}</div>
          <Row icon="fa-database" label="Data source" text={info.source} color="rgb(125,178,255)" />
          {info.method && <Row icon="fa-function" label="How it's calculated" text={info.method} color="rgb(94,214,164)" />}
          {info.cadence && <Row icon="fa-clock-3" label="Refresh cadence" text={info.cadence} color="rgb(196,181,253)" />}
        </div>
      ), document.body)}
    </span>
  );
}

function Tile({ title, children, onMore, style, footLabel }) {
  const ref = React.useRef();
  const period = React.useContext(PeriodContext);
  const label = footLabel || periodToLabel(period);
  const handleMore = () => {
    if (typeof onMore === 'function') onMore();
    else window.dispatchEvent(new CustomEvent('tile:see-more', { detail: { title } }));
  };
  return (
    <div ref={ref} style={{ ...TILE, ...style }}>
      <div style={TILE_HEAD}>
        <div style={TILE_TITLE}>{title}</div>
        <TileInfo title={title} />
        <button className="tile-overflow-btn" style={{ ...OVERFLOW, marginLeft:'auto' }} aria-label="More"><i className="fa-solid fa-ellipsis" style={{ width:14, height:14 }} /></button>
      </div>
      <div style={TILE_BODY}>{children}</div>
      <div style={TILE_FOOT}>
        <span>{label}</span>
        <a style={SEE_MORE} onClick={handleMore}>See more <i className="fa-solid fa-chevron-right" style={{ width:12, height:12 }} /></a>
      </div>
    </div>
  );
}

/* 1. Upcoming Meetings ---------------------------------------------------- */
function UpcomingMeetings({ onMore }) {
  const rows = [
    { d:'02', m:'FEB', t:'Kyung Min Meeting',        time:'11:00AM –12:00PM', badge:'NEW' },
    { d:'03', m:'FEB', t:'David Young Performance Meeting', time:'1:00PM –2:00PM' },
    { d:'04', m:'FEB', t:'Market Outlook Discussion', time:'1:00PM –2:00PM' },
    { d:'06', m:'FEB', t:'Risk Management Review',    time:'1:00PM –2:00PM' },
    { d:'08', m:'FEB', t:'Legacy Planning Session',   time:'1:00PM –2:00PM' },
  ];
  return (
    <Tile title="Upcoming Meetings" onMore={onMore} footLabel="Updated: May 13, 2026">
      <div style={{ display:'flex', flexDirection:'column' }}>
        {rows.map((r,i) => (
          <div key={i} style={{ display:'flex', alignItems:'center', gap:12, padding:'10px 0', borderTop: i? '1px solid rgba(75,85,99,0.45)':'none' }}>
            <div style={{ width:36, textAlign:'center' }}>
              <div style={{ fontFamily:'Inter', fontSize:10, color:'rgb(163,163,163)', letterSpacing:'0.08em' }}>{r.m}</div>
              <div style={{ fontFamily:'Inter', fontWeight:700, fontSize:18, color:'rgb(5,122,85)', lineHeight:1 }}>{r.d}</div>
            </div>
            <div style={{ flex:1, minWidth:0 }}>
              <div style={{ display:'flex', alignItems:'center', gap:8 }}>
                <span style={{ fontFamily:'Inter', fontWeight:500, fontSize:13, color:'rgb(249,250,251)', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{r.t}</span>
                {r.badge && <span style={{
                  background:'rgb(5,122,85)', color:'#fff', fontFamily:'Inter', fontWeight:700, fontSize:10,
                  padding:'2px 7px', borderRadius:9999, letterSpacing:'0.04em',
                }}>{r.badge}</span>}
              </div>
              <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)' }}>{r.time}</div>
            </div>
          </div>
        ))}
      </div>
    </Tile>
  );
}

/* 2. Notifications -------------------------------------------------------- */
function Notifications({ onMore }) {
  const rows = [
    { icon:'calendar-circle-user', tone:'success', title:'Upcoming Meeting: David Young', body:'Tomorrow at 10:30 AM — prepare meeting brief and review prior notes', tag:'Prep', tagTone:'success', action:'prep_meeting' },
    { icon:'check-circle-2', tone:'warning', title:'Proposal Approved', body:'Maria Workman has approved the investment proposal. Next step…', tag:'In 3 days', tagTone:'warning' },
    { icon:'envelope', tone:'info', title:'New Client Reply', body:'Robert Patel responded to your Q4 review email — needs follow-up', tag:'New', tagTone:'info' },
    { icon:'file-signature', tone:'info', title:'Document Signed', body:'Edwards Family signed advisory agreement — ready to file', tag:'Signed', tagTone:'success' },
  ];
  const TONE = {
    info:    { bg:'rgba(59,130,246,0.10)', ring:'rgba(59,130,246,0.35)', fg:'rgb(147,197,253)' },
    success: { bg:'rgba(5,122,85,0.12)',   ring:'rgba(5,122,85,0.45)',   fg:'rgb(16,185,129)'  },
    danger:  { bg:'rgba(220,38,38,0.10)',  ring:'rgba(220,38,38,0.45)',  fg:'rgb(248,113,113)' },
    warning: { bg:'rgba(234,179,8,0.10)',  ring:'rgba(234,179,8,0.40)',  fg:'rgb(234,179,8)'   },
    mute:    { bg:'rgba(255,255,255,0.03)', ring:'rgba(75,85,99,0.6)',   fg:'rgb(163,163,163)' },
  };
  const TAG = {
    info:    { bg:'rgb(37,99,235)',  fg:'#fff' },
    success: { bg:'rgb(5,122,85)',   fg:'#fff' },
    danger:  { bg:'rgb(220,38,38)',  fg:'#fff' },
    warning: { bg:'rgba(234,179,8,0.2)',  fg:'rgb(253,224,71)', border:'1px solid rgba(234,179,8,0.5)' },
    mute:    { bg:'rgba(17,24,39,0.8)', fg:'rgb(229,231,235)', border:'1px solid rgb(75,85,99)' },
  };
  return (
    <Tile title="Notifications" onMore={onMore} footLabel="Updated: May 13, 2026">
      <div style={{ display:'flex', flexDirection:'column', gap:8, paddingTop:4 }}>
        {rows.map((r,i) => {
          const t = TONE[r.tone];
          const tg = TAG[r.tagTone];
          const isClickable = r.action === 'prep_meeting';
          return (
            <div
              key={i}
              onClick={isClickable ? (() => window.dispatchEvent(new CustomEvent('client:open', { detail:{ client:'David Young', highlight:'prep_meeting' } }))) : undefined}
              style={{
                display:'grid', gridTemplateColumns:'32px 1fr auto', alignItems:'center', gap:12,
                padding:'10px 12px', borderRadius:10,
                background:t.bg, border:`1px solid ${t.ring}`,
                cursor: isClickable ? 'pointer' : 'default',
                transition:'transform 150ms ease, border-color 150ms ease',
              }}
              onMouseEnter={isClickable ? (e) => { e.currentTarget.style.borderColor = 'rgb(16,185,129)'; e.currentTarget.style.transform = 'translateY(-1px)'; } : undefined}
              onMouseLeave={isClickable ? (e) => { e.currentTarget.style.borderColor = t.ring; e.currentTarget.style.transform = 'translateY(0)'; } : undefined}
            >
              <div style={{
                width:32, height:32, borderRadius:9999, background:'rgba(17,24,39,0.6)',
                border:`1px solid ${t.ring}`, display:'flex', alignItems:'center', justifyContent:'center',
              }}>
                <i className={faCls(r.icon)} style={{ width:16, height:16, color:t.fg }} />
              </div>
              <div style={{ minWidth:0 }}>
                <div style={{ fontFamily:'Inter', fontSize:12.5, fontWeight:600, color:'rgb(249,250,251)', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{r.title}</div>
                <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{r.body}</div>
              </div>
              <span style={{
                fontFamily:'Inter', fontWeight:600, fontSize:10.5, padding:'3px 10px', borderRadius:9999,
                ...tg,
              }}>{r.tag}</span>
            </div>
          );
        })}
      </div>
    </Tile>
  );
}

/* 3. Opportunities -------------------------------------------------------- */
function Opportunities({ onMore }) {
  const rows = [
    { icon:'arrows-rotate', color:'rgb(16,185,129)',iconBg:'rgba(5,122,85,0.18)', title:'Portfolio Rebalance', subtitle:'David Young', clients:1,  val:'$2.4M', action:'rebalance' },
    { icon:'lightbulb',color:'rgb(110,231,183)', iconBg:'rgba(5,122,85,0.18)', title:'New Insights', subtitle:'Halo · BlackRock · PIMCO · Blackstone', clients:14, val:'$1.6M', action:'insights' },
    { icon:'target',      color:'rgb(220,38,38)',  iconBg:'rgba(220,38,38,0.12)',  title:'Tax-Managed Public Equity', clients:14, val:'$18.4M' },
    { icon:'briefcase',   color:'rgb(59,130,246)', iconBg:'rgba(59,130,246,0.12)', title:'State Portfolio',           clients:9,  val:'$14.2M' },
    { icon:'droplet',     color:'rgb(234,179,8)',  iconBg:'rgba(234,179,8,0.12)',  title:'Strategic Liquidation Program', clients:7, val:'$11.6M' },
  ];
  return (
    <Tile title="Opportunities" onMore={onMore}>
      <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', padding:'0 0 6px' }}>Overnight Analysis</div>
      <div style={{ display:'flex', flexDirection:'column' }}>
        {rows.map((r,i) => {
          const isClickable = !!r.action;
          const onRowClick = () => {
            if (r.action === 'rebalance') window.dispatchEvent(new CustomEvent('client:open', { detail:{ client:'David Young', highlight:'rebalance' } }));
            else if (r.action === 'insights') window.dispatchEvent(new CustomEvent('insights:scan'));
          };
          return (
            <div
              key={i}
              onClick={isClickable ? onRowClick : undefined}
              style={{
                display:'grid', gridTemplateColumns:'32px 1fr auto', alignItems:'center', gap:12,
                padding:'10px 8px', margin:'0 -8px',
                borderTop:i?'1px solid rgba(75,85,99,0.45)':'none',
                cursor: isClickable ? 'pointer' : 'default',
                borderRadius: isClickable ? 8 : 0,
                transition:'background 150ms ease',
                position:'relative',
              }}
              onMouseEnter={isClickable ? (e) => e.currentTarget.style.background='rgba(5,122,85,0.08)' : undefined}
              onMouseLeave={isClickable ? (e) => e.currentTarget.style.background='transparent' : undefined}
            >
              <div style={{ width:32, height:32, borderRadius:9999, background:r.iconBg, display:'flex', alignItems:'center', justifyContent:'center' }}>
                <i className={faCls(r.icon)} style={{ width:16, height:16, color:r.color }} />
              </div>
              <div style={{ minWidth:0 }}>
                <div style={{ fontFamily:'Inter', fontSize:13, fontWeight:500, display:'flex', alignItems:'center', gap:8 }}>
                  {r.title}
                  {isClickable && <i className="fa-solid fa-sparkles" style={{ width:10, height:10, color:'rgb(16,185,129)' }} />}
                </div>
                {r.subtitle && (
                  <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', marginTop:2 }}>{r.subtitle}</div>
                )}
              </div>
              <div style={{ fontFamily:'Inter', fontSize:12, color:'rgb(163,163,163)' }}>{r.clients} client{r.clients !== 1 ? 's' : ''}</div>
            </div>
          );
        })}
      </div>
    </Tile>
  );
}

/* 4. Top Clients (8 cards in 4×2 grid) ------------------------------------ */
const TOP_CLIENTS_BY_PERIOD = {
  'Today': {
    suffix: 'TODAY',
    cards: [
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'0.42%' , aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'0.61%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'down', pct:'0.18%' , aum:'$1.4M',  accent:'rgb(248,113,113)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'0.09%' , aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'0.34%' , aum:null,     accent:'rgb(248,113,113)' },
      { name:'Chance Curtis',  review:'5 month ago',  dir:'up',   pct:'0.22%' , aum:'$1M',    accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'0.15%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'0.51%' , aum:'$2.4M',  accent:'rgb(5,122,85)' },
    ],
  },
  'This week': {
    suffix: 'WK',
    cards: [
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'1.84%' , aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'2.41%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'up',   pct:'0.62%' , aum:'$1.4M',  accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'2.10%' , aum:'$2.4M',  accent:'rgb(5,122,85)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'0.31%' , aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'0.84%' , aum:null,     accent:'rgb(248,113,113)' },
      { name:'Chance Curtis',  review:'5 month ago',  dir:'up',   pct:'0.74%' , aum:'$1M',    accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'0.52%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
    ],
  },
  'This month': {
    suffix: 'MTD',
    cards: [
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'5.82%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'4.61%' , aum:'$2.4M',  accent:'rgb(5,122,85)' },
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'3.94%' , aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'Edwards Family', review:'2 month ago',  dir:'up',   pct:'3.18%' , aum:'$1.6M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'up',   pct:'2.42%' , aum:'$1.4M',  accent:'rgb(5,122,85)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'1.21%' , aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'1.84%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'1.12%' , aum:null,     accent:'rgb(248,113,113)' },
    ],
  },
  'This quarter': {
    suffix: 'QTD',
    cards: [
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'9.41%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'7.82%' , aum:'$2.4M',  accent:'rgb(5,122,85)' },
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'6.34%' , aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'Edwards Family', review:'2 month ago',  dir:'up',   pct:'5.91%' , aum:'$1.6M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'up',   pct:'4.22%' , aum:'$1.4M',  accent:'rgb(5,122,85)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'2.18%' , aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'3.42%' , aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'0.84%' , aum:null,     accent:'rgb(248,113,113)' },
    ],
  },
  'Year to date': {
    suffix: 'YTD',
    cards: [
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'10.68%', aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'23.68%', aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'up',   pct:'7.68%',  aum:'$1.4M',  accent:'rgb(5,122,85)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'2.68%',  aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'0.68%',  aum:null,     accent:'rgb(248,113,113)' },
      { name:'Chance Curtis',  review:'5 month ago',  dir:'up',   pct:'7.28%',  aum:'$1M',    accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'4.68%',  aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'9.68%',  aum:'$2.4M',  accent:'rgb(5,122,85)' },
    ],
  },
  'Last 12 months': {
    suffix: '12mo',
    cards: [
      { name:'John Smith',     review:'Year ago',     dir:'up',   pct:'34.21%', aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Maria Workman',  review:'3 month ago',  dir:'up',   pct:'21.84%', aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'1 month ago',  dir:'up',   pct:'18.42%', aum:'$2.4M',  accent:'rgb(5,122,85)' },
      { name:'Edwards Family', review:'2 month ago',  dir:'up',   pct:'15.31%', aum:'$1.6M',  accent:'rgb(5,122,85)' },
      { name:'Zaire Herwitz',  review:'6 month ago',  dir:'up',   pct:'12.45%', aum:'$1.4M',  accent:'rgb(5,122,85)' },
      { name:'Alfonso Mango',  review:'2 month ago',  dir:'up',   pct:'9.62%',  aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Ryan Korsgaard', review:'7 month ago',  dir:'up',   pct:'6.18%',  aum:'$1.3M',  accent:'rgb(5,122,85)' },
      { name:'Mira Aminoff',   review:'4 month ago',  dir:'down', pct:'2.41%',  aum:null,     accent:'rgb(248,113,113)' },
    ],
  },
  'All time': {
    suffix: 'TOTAL',
    cards: [
      { name:'Smith Trust',    review:'Client since 2014', dir:'up', pct:'214.6%', aum:'$28.9M', accent:'rgb(5,122,85)' },
      { name:'Hawkins Family', review:'Client since 2016', dir:'up', pct:'182.4%', aum:'$29.4M', accent:'rgb(5,122,85)' },
      { name:'Watson Holdings',review:'Client since 2017', dir:'up', pct:'164.3%', aum:'$27.2M', accent:'rgb(5,122,85)' },
      { name:'Maria Workman',  review:'Client since 2018', dir:'up', pct:'142.8%', aum:'$2M',    accent:'rgb(5,122,85)' },
      { name:'John Smith',     review:'Client since 2019', dir:'up', pct:'118.4%', aum:'$1.8M',  accent:'rgb(5,122,85)' },
      { name:'Jones Family',   review:'Client since 2020', dir:'up', pct:'96.2%',  aum:'$18.1M', accent:'rgb(5,122,85)' },
      { name:'Lang Trust',     review:'Client since 2021', dir:'up', pct:'82.4%',  aum:'$16.4M', accent:'rgb(5,122,85)' },
      { name:'David Young',    review:'Client since 2022', dir:'up', pct:'68.1%',  aum:'$2.4M',  accent:'rgb(5,122,85)' },
    ],
  },
};

function TopClients({ onMore }) {
  const period = React.useContext(PeriodContext);
  const cfg = TOP_CLIENTS_BY_PERIOD[period] || TOP_CLIENTS_BY_PERIOD['Year to date'];
  const cards = cfg.cards;
  return (
    <Tile title="Top Clients" onMore={onMore}>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:10, paddingTop:4 }}>
        {cards.map((c,i) => {
          const ref = React.useRef();
          return (
            <div key={i} ref={ref} style={{
              position:'relative', padding:'10px 12px 10px 14px',
              border:'1px solid rgba(75,85,99,0.6)', borderRadius:10,
              background:'rgba(255,255,255,0.015)',
            }}>
              <div style={{ position:'absolute', left:0, top:10, bottom:10, width:3, borderRadius:9999, background:c.accent }} />
              <div style={{ fontFamily:'Inter', fontSize:12.5, fontWeight:600, color:'rgb(249,250,251)', marginBottom:4 }}>{c.name}</div>
              <div style={{ fontFamily:'Inter', fontSize:10.5, color:'rgb(163,163,163)' }}>Last Review: {c.review}</div>
              <div style={{ fontFamily:'Inter', fontSize:10.5, color:'rgb(163,163,163)', marginTop:6 }}>Perf.</div>
              <div style={{ display:'flex', alignItems:'center', gap:4 }}>
                <i className={`fa-solid fa-${(c.dir==='up'?'arrow-up':'arrow-down').replace(/^fa-/,'')}`} style={{ width:12, height:12, color:c.accent }} />
                <span style={{ fontFamily:'Inter', fontVariantNumeric:'tabular-nums', fontSize:12, fontWeight:600, color:c.accent }}>{c.pct}</span>
                <span style={{ fontFamily:'Inter', fontSize:10, color:'rgb(163,163,163)' }}>{cfg.suffix}</span>
              </div>
              {c.aum && <>
                <div style={{ fontFamily:'Inter', fontSize:10.5, color:'rgb(163,163,163)', marginTop:4 }}>Total AUM</div>
                <div style={{ fontFamily:'Inter', fontVariantNumeric:'tabular-nums', fontSize:12.5, fontWeight:600, color:'rgb(249,250,251)' }}>{c.aum}</div>
              </>}
            </div>
          );
        })}
      </div>
    </Tile>
  );
}

/* 5. Billing Summary ------------------------------------------------------ */
const BILLING_BY_PERIOD = {
  'Today': {
    stats: [
      { label:"Today's Fees",     value:'$1,280',   delta:'+$190 vs avg day',  tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',  tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection', tone:'success' },
    ],
    chart: { categories:['9a','10a','11a','12p','1p','2p','3p','4p'], data:[0.14,0.18,0.22,0.16,0.12,0.20,0.18,0.10] },
  },
  'This week': {
    stats: [
      { label:'Weekly Fees',      value:'$5,840',   delta:'+12% vs prior week',  tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',    tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection',   tone:'success' },
    ],
    chart: { categories:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], data:[0.86,0.92,0.78,1.04,0.94,0.62,0.68] },
  },
  'This month': {
    stats: [
      { label:'MTD Fees',         value:'$16,520',  delta:'+4.5% vs Apr',        tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',    tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection',   tone:'success' },
    ],
    chart: { categories:['W1','W2','W3','W4'], data:[3.8,4.2,4.1,4.4] },
  },
  'This quarter': {
    stats: [
      { label:'QTD Fees',         value:'$32,610',  delta:'+8.1% vs Q1',         tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',    tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection',   tone:'success' },
    ],
    chart: { categories:['Apr','May'], data:[16.10,16.51] },
  },
  'Year to date': {
    stats: [
      { label:'YTD Billable Assets', value:'$16.5M',   delta:'+5.8% vs prior YTD',   tone:'success' },
      { label:'YTD Fees Collected',  value:'$78,400',  delta:'+$4,210 vs prior YTD', tone:'success' },
      { label:'Fee Run Rate',        value:'$175,996', delta:'Annual projection',    tone:'success' },
    ],
    chart: { categories:['Jan','Feb','Mar','Apr','May'], data:[14.2,14.8,15.4,16.1,17.9] },
  },
  'Last 12 months': {
    stats: [
      { label:'12-mo Fees',       value:'$172,840', delta:'+8.6% YoY',           tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',    tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection',   tone:'success' },
    ],
    chart: { categories:['Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May'], data:[12.8,13.1,13.4,13.6,13.8,14.0,14.4,14.2,14.8,15.4,16.1,17.9] },
  },
  'All time': {
    stats: [
      { label:'Lifetime Fees',    value:'$684,200', delta:'Since 2020',          tone:'success' },
      { label:'Billable Assets',  value:'$16.5M',   delta:'Current snapshot',    tone:'success' },
      { label:'Fee Run Rate',     value:'$175,996', delta:'Annual projection',   tone:'success' },
    ],
    chart: { categories:['2020','2021','2022','2023','2024','2025','2026'], data:[82,96,112,128,142,165,78] },
  },
};

function BillingSummary({ onMore }) {
  const period = React.useContext(PeriodContext);
  const cfg = BILLING_BY_PERIOD[period] || BILLING_BY_PERIOD['Year to date'];
  const opts = React.useMemo(() => ({
    chart: { type:'area', height: 220, spacing:[10, 8, 4, 4] },
    xAxis: {
      categories: cfg.chart.categories,
      tickLength: 0,
    },
    yAxis: {
      title: { text: null },
      labels: { formatter: function () { return '$' + this.value + 'K'; } },
    },
    tooltip: { valuePrefix: '$', valueSuffix: 'K', valueDecimals: 1 },
    plotOptions: {
      area: {
        fillColor: {
          linearGradient: { x1:0, y1:0, x2:0, y2:1 },
          stops: [[0, 'rgba(5,122,85,0.35)'], [1, 'rgba(5,122,85,0)']],
        },
        lineWidth: 2, color: 'rgb(5,122,85)',
        marker: { enabled: true, radius: 3.5, fillColor: 'rgb(10,10,10)', lineColor:'rgb(5,122,85)', lineWidth: 2 },
      },
    },
    series: [{ name:'Fees', data: cfg.chart.data }],
    legend: { enabled: false },
  }), [period]);
  return (
    <Tile title="Billing Summary" onMore={onMore}>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:10, paddingTop:4 }}>
        {cfg.stats.map((s,i)=>(
          <div key={i} style={{ border:'1px solid rgb(75,85,99)', borderRadius:10, padding:'14px 14px', background:'rgba(255,255,255,0.02)' }}>
            <div style={{ fontFamily:'Inter', fontSize:12, color:'rgb(163,163,163)', marginBottom:6 }}>{s.label}</div>
            <div style={{ fontFamily:'Inter', fontWeight:700, fontSize:20, letterSpacing:'-0.01em', color:'rgb(249,250,251)', marginBottom:8, fontVariantNumeric:'tabular-nums' }}>{s.value}</div>
            <div style={{ fontFamily:'Inter', fontSize:12, color:'rgb(5,122,85)', display:'flex', alignItems:'center', gap:6 }}>
              <i className="fa-solid fa-arrow-up" style={{ fontSize:10 }} />
              <span>{s.delta}</span>
            </div>
          </div>
        ))}
      </div>
      <div style={{ flex:1, minHeight:220, marginTop:14 }}>
        <HC options={opts} />
      </div>
    </Tile>
  );
}

/* 6. Content Hub --------------------------------------------------------- */
function ContentHub({ onMore }) {
  const rows = [
    { who:'Michael Gray',   when:'4 days ago' },
    { who:'Jon Hummill',    when:'1 day ago'  },
    { who:'Andrew King',    when:'2 days ago' },
    { who:'Chris Jones',    when:'3 days ago' },
  ];
  return (
    <Tile title="Content Hub" onMore={onMore}>
      <div style={{ display:'grid', gridTemplateColumns:'140px 1fr', gap:14, paddingTop:4, flex:1, minHeight:0 }}>
        <div style={{
          borderRadius:10, overflow:'hidden',
          background:'linear-gradient(160deg, rgb(120,143,182) 0%, rgb(70,92,126) 60%, rgb(30,47,76) 100%)',
          position:'relative',
        }}>
          {/* stylized skyscraper via CSS */}
          <div style={{ position:'absolute', inset:0, background:
            'repeating-linear-gradient(90deg, rgba(255,255,255,0.04) 0 6px, transparent 6px 9px), ' +
            'repeating-linear-gradient(0deg, rgba(255,255,255,0.06) 0 5px, transparent 5px 8px)' }} />
          <div style={{ position:'absolute', left:'18%', right:'10%', bottom:0, top:'22%',
            background:'linear-gradient(180deg, rgba(20,30,50,0.7), rgba(10,14,24,0.95))',
            clipPath:'polygon(0 15%, 30% 8%, 30% 0, 70% 0, 70% 6%, 100% 12%, 100% 100%, 0 100%)' }} />
        </div>
        <div style={{ display:'flex', flexDirection:'column' }}>
          {rows.map((r,i) => (
            <div key={i} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'9px 0', borderTop:i?'1px solid rgba(75,85,99,0.45)':'none' }}>
              <span style={{ fontFamily:'Inter', fontSize:12.5, fontWeight:500 }}>{r.who}</span>
              <span style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)' }}>{r.when}</span>
            </div>
          ))}
        </div>
      </div>
    </Tile>
  );
}

/* 7. AUM Asset Allocation (donut OR bar chart) -------------------------- */
function AumAllocation({ onMore, variant = 'donut' }) {
  const slices = [
    { v:0.28, arc:'rgba( 94, 214, 164, 0.5)', dot:'rgb( 94, 214, 164)', label:'Equities' },
    { v:0.18, arc:'rgba(120, 160, 230, 0.5)', dot:'rgb(120, 160, 230)', label:'Fixed Income' },
    { v:0.14, arc:'rgba(180, 150, 235, 0.5)', dot:'rgb(180, 150, 235)', label:'Alternatives' },
    { v:0.12, arc:'rgba(245, 200,  90, 0.5)', dot:'rgb(245, 200,  90)', label:'Private' },
    { v:0.10, arc:'rgba(240, 140, 120, 0.5)', dot:'rgb(240, 140, 120)', label:'Real Estate' },
    { v:0.08, arc:'rgba(120, 200, 210, 0.5)', dot:'rgb(120, 200, 210)', label:'Cash' },
    { v:0.06, arc:'rgba(200, 170, 130, 0.5)', dot:'rgb(200, 170, 130)', label:'Hedge' },
    { v:0.04, arc:'rgba(160, 170, 185, 0.5)', dot:'rgb(160, 170, 185)', label:'Other' },
  ];
  const donutOpts = React.useMemo(() => ({
    chart: { type:'pie', height: 240, spacing:[4,4,4,4] },
    tooltip: {
      pointFormatter: function () {
        return `<span style="color:${this.color}">●</span> <b>${this.name}</b>: ${Math.round(this.y*100)}%`;
      },
    },
    plotOptions: {
      pie: {
        innerSize: '68%',
        borderColor: 'rgb(10,10,10)',
        borderWidth: 1,
        borderRadius: 0,
        dataLabels: { enabled: false },
        states: { hover: { brightness: 0.08, halo: { size: 6, opacity: 0.2 } } },
      },
    },
    series: [{
      name: 'Allocation',
      data: slices.map(s => ({ name: s.label, y: s.v, color: s.arc, borderColor: s.dot })),
    }],
  }), []);
  const barOpts = React.useMemo(() => ({
    chart: { type:'bar', height: 280, spacing:[8,4,4,4], backgroundColor:'transparent', animation: false },
    xAxis: {
      categories: slices.map(s => s.label),
      lineColor: 'rgba(75,85,99,0.4)',
      tickColor: 'transparent',
      labels: { style: { color: 'rgb(229,231,235)', fontFamily:'Inter', fontSize:'11px' } },
    },
    yAxis: {
      min: 0, max: 0.32,
      title: { text: null },
      gridLineColor: 'rgba(75,85,99,0.25)',
      gridLineDashStyle: 'Dash',
      labels: {
        style: { color: 'rgb(163,163,163)', fontFamily:'Inter', fontSize:'10px' },
        formatter: function () { return Math.round(this.value*100) + '%'; },
      },
    },
    tooltip: {
      pointFormatter: function () {
        return `<span style="color:${this.color}">●</span> <b>${this.category}</b>: ${Math.round(this.y*100)}%`;
      },
    },
    plotOptions: {
      bar: {
        borderRadius: 4,
        borderWidth: 0,
        pointPadding: 0.08,
        groupPadding: 0.06,
        animation: false,
        dataLabels: {
          enabled: true,
          align: 'left',
          inside: false,
          style: { color: 'rgb(249,250,251)', fontFamily:'Inter', fontWeight:'500', fontSize:'10.5px', textOutline:'none' },
          formatter: function () { return Math.round(this.y*100) + '%'; },
        },
      },
    },
    series: [{
      name: 'Allocation',
      data: slices.map(s => ({ name: s.label, y: s.v, color: s.arc, borderColor: s.dot, borderWidth: 1.5 })),
    }],
  }), []);
  return (
    <Tile title="AUM Asset Allocation" onMore={onMore}>
      {variant === 'bar' ? (
        <div style={{ paddingTop:4 }}>
          <div style={{ width:'100%' }}>
            <HC options={barOpts} />
          </div>
          <div style={{ display:'flex', alignItems:'baseline', justifyContent:'space-between', marginTop:6, paddingTop:8, borderTop:'1px solid rgba(75,85,99,0.35)' }}>
            <div style={{ fontFamily:'Inter', fontSize:10, letterSpacing:'0.12em', color:'rgb(163,163,163)', textTransform:'uppercase' }}>Total Value</div>
            <div style={{ fontFamily:'Inter', fontSize:18, fontWeight:600, color:'rgb(249,250,251)', fontVariantNumeric:'tabular-nums', letterSpacing:'-0.01em' }}>$42.3M</div>
          </div>
        </div>
      ) : (
      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:18, paddingTop:4, alignItems:'center' }}>
        <div style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:10, position:'relative' }}>
          <div style={{ width:'100%', maxWidth:240, aspectRatio:'1 / 1', position:'relative' }}>
            <HC options={donutOpts} />
            <div style={{
              position:'absolute', inset:0, display:'flex', flexDirection:'column',
              alignItems:'center', justifyContent:'center', pointerEvents:'none', textAlign:'center',
            }}>
              <div style={{ fontFamily:'Inter', fontSize:10, letterSpacing:'0.12em', color:'rgb(163,163,163)', textTransform:'uppercase' }}>Total Value</div>
              <div style={{ fontFamily:'Inter', fontSize:22, fontWeight:600, color:'rgb(249,250,251)', fontVariantNumeric:'tabular-nums', letterSpacing:'-0.01em', marginTop:2 }}>$42.3M</div>
            </div>
          </div>
        </div>
        <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
          {slices.map((s,i) => (
            <div key={i} style={{ display:'flex', alignItems:'center', gap:10, fontFamily:'Inter', fontSize:12 }}>
              <span style={{ width:8, height:8, borderRadius:9999, background:s.dot, flexShrink:0 }} />
              <span style={{ flex:1, color:'rgb(229,231,235)' }}>{s.label}</span>
              <span style={{ fontFamily:'Inter', fontVariantNumeric:'tabular-nums', color:'rgb(163,163,163)' }}>{Math.round(s.v*100)}%</span>
            </div>
          ))}
        </div>
      </div>
      )}
    </Tile>
  );
}

/* 8. Assets Under Management (horizontal bars) --------------------------- */
function AumBars({ onMore }) {
  const rows = [
    { label:'Qualified Retirement', aum:780, hold:220 },
    { label:'Taxable Investment',   aum:640, hold:180 },
    { label:'Cash Equivalent',      aum:500, hold:280 },
    { label:'Life Insurance',       aum:400, hold:220 },
    { label:'Other',                aum:180, hold:100 },
  ];
  const opts = React.useMemo(() => ({
    chart: { type:'bar', height: 260, spacing:[8, 4, 8, 4] },
    xAxis: {
      categories: rows.map(r => r.label),
      lineColor: 'transparent',
      tickLength: 0,
      labels: { style: { color: 'rgb(229,231,235)', fontSize: '12px' } },
    },
    yAxis: {
      min: 0, max: 900,
      tickPositions: [0, 300, 500, 700, 800, 900],
      labels: { formatter: function () { return this.value === 0 ? '$0' : '$' + this.value + 'M'; } },
      gridLineDashStyle: 'Dash',
      opposite: false,
    },
    tooltip: {
      shared: true,
      pointFormat: '<span style="color:{series.color}">\u25CF</span> {series.name}: <b>${point.y}M</b><br/>',
    },
    legend: { enabled: false },
    plotOptions: {
      series: {
        stacking: 'normal',
        pointPadding: 0.15,
        groupPadding: 0.1,
        borderRadius: 3,
      },
    },
    series: [
      { name:'Assets Under Management', color:'rgba(5,122,85,0.45)',   borderColor:'rgb(5,122,85)',   borderWidth:1.5, data: rows.map(r => r.aum) },
      { name:'Assets Held Away',        color:'rgba(160,170,185,0.45)', borderColor:'rgb(160,170,185)', borderWidth:1.5, data: rows.map(r => r.hold) },
    ],
  }), []);
  return (
    <Tile title="Assets Under Management" onMore={onMore}>
      <div style={{ display:'flex', gap:16, fontFamily:'Inter', fontSize:12, color:'rgb(163,163,163)', paddingTop:2, paddingBottom:6 }}>
        <span style={{ display:'flex', alignItems:'center', gap:6 }}><span style={{ width:8, height:8, borderRadius:2, background:'rgb(5,122,85)' }} /> Assets Under Management</span>
        <span style={{ display:'flex', alignItems:'center', gap:6 }}><span style={{ width:8, height:8, borderRadius:2, background:'rgb(160,170,185)' }} /> Assets Held Away</span>
      </div>
      <div style={{ flex:1, minHeight:260 }}>
        <HC options={opts} />
      </div>
    </Tile>
  );
}

/* 9. Cash Flow (stacked bars) -------------------------------------------- */
const CASHFLOW_BY_PERIOD = {
  'Today': {
    stats: [
      { label:"Today's Inflows",  value:'$1.2M',  color:'rgb(5,122,85)' },
      { label:"Today's Outflows", value:'-$0.4M', color:'rgb(248,113,113)' },
      { label:"Today's Net",      value:'$0.8M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['9a','10a','11a','12p','1p','2p','3p','4p'], inflow:[0.18,0.24,0.16,0.12,0.10,0.18,0.14,0.08], outflow:[-0.04,-0.08,-0.06,-0.02,-0.04,-0.06,-0.08,-0.02] },
  },
  'This week': {
    stats: [
      { label:'Inflows',  value:'$8.5M',  color:'rgb(5,122,85)' },
      { label:'Outflows', value:'-$3.1M', color:'rgb(248,113,113)' },
      { label:'Net Flow', value:'$5.4M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], inflow:[1.2,1.6,0.9,1.4,1.8,0.8,0.8], outflow:[-0.4,-0.6,-0.3,-0.5,-0.7,-0.3,-0.3] },
  },
  'This month': {
    stats: [
      { label:'MTD Inflows',  value:'$31M', color:'rgb(5,122,85)' },
      { label:'MTD Outflows', value:'-$9M', color:'rgb(248,113,113)' },
      { label:'MTD Net Flow', value:'$22M', color:'rgb(249,250,251)' },
    ],
    chart: { categories:['W1','W2'], inflow:[16,15], outflow:[-4,-5] },
  },
  'This quarter': {
    stats: [
      { label:'QTD Inflows',  value:'$57M',  color:'rgb(5,122,85)' },
      { label:'QTD Outflows', value:'-$19M', color:'rgb(248,113,113)' },
      { label:'QTD Net Flow', value:'$38M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['Apr','May'], inflow:[26,31], outflow:[-10,-9] },
  },
  'Year to date': {
    stats: [
      { label:'YTD Inflows',  value:'$126.0M', color:'rgb(5,122,85)' },
      { label:'YTD Outflows', value:'-$45.0M', color:'rgb(248,113,113)' },
      { label:'YTD Net Flow', value:'$81.0M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['Jan','Feb','Mar','Apr','May'], inflow:[22,28,19,26,31], outflow:[-8,-11,-7,-10,-9] },
  },
  'Last 12 months': {
    stats: [
      { label:'12-mo Inflows',  value:'$268M',  color:'rgb(5,122,85)' },
      { label:'12-mo Outflows', value:'-$98M',  color:'rgb(248,113,113)' },
      { label:'12-mo Net Flow', value:'$170M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May'], inflow:[18,20,15,22,17,19,21,22,28,19,26,31], outflow:[-6,-8,-5,-9,-7,-8,-9,-8,-11,-7,-10,-9] },
  },
  'All time': {
    stats: [
      { label:'Lifetime Inflows',  value:'$1.2B',  color:'rgb(5,122,85)' },
      { label:'Lifetime Outflows', value:'-$420M', color:'rgb(248,113,113)' },
      { label:'Lifetime Net',      value:'$780M',  color:'rgb(249,250,251)' },
    ],
    chart: { categories:['2020','2021','2022','2023','2024','2025','2026'], inflow:[140,165,180,195,215,250,126], outflow:[-55,-62,-68,-72,-80,-88,-45] },
  },
};

function CashFlow({ onMore }) {
  const period = React.useContext(PeriodContext);
  const cfg = CASHFLOW_BY_PERIOD[period] || CASHFLOW_BY_PERIOD['Year to date'];
  const stats = cfg.stats;
  const opts = React.useMemo(() => ({
    chart: { type:'column', height: 200, spacing:[8, 4, 4, 4] },
    xAxis: {
      categories: cfg.chart.categories,
      tickLength: 0,
      lineColor: 'rgba(75,85,99,0.6)',
    },
    yAxis: {
      title: { text: null },
      labels: { formatter: function () { return '$' + this.value + 'M'; } },
      plotLines: [{ value: 0, color: 'rgba(75,85,99,0.6)', width: 1, dashStyle: 'Dash', zIndex: 4 }],
    },
    tooltip: {
      shared: true,
      pointFormatter: function () {
        const sign = this.y < 0 ? '-$' : '$';
        return `<span style="color:${this.color}">\u25CF</span> ${this.series.name}: <b>${sign}${Math.abs(this.y)}M</b><br/>`;
      },
    },
    legend: { enabled: false },
    plotOptions: {
      column: {
        pointPadding: 0.12,
        groupPadding: 0.12,
        borderRadius: 2,
      },
    },
    series: [
      { name:'Inflow',  color:'rgba(5,122,85,0.45)',  borderColor:'rgb(5,122,85)',  borderWidth:1.5, data: cfg.chart.inflow  },
      { name:'Outflow', color:'rgba(220,38,38,0.45)', borderColor:'rgb(220,38,38)', borderWidth:1.5, data: cfg.chart.outflow },
    ],
  }), [period]);
  return (
    <Tile title="Cash Flow" onMore={onMore}>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:8, paddingTop:4 }}>
        {stats.map((s,i)=>(
          <div key={i} style={{ border:'1px solid rgb(75,85,99)', borderRadius:8, padding:'8px 10px' }}>
            <div style={{ fontFamily:'Inter', fontSize:10, color:'rgb(163,163,163)' }}>{s.label}</div>
            <div style={{ fontFamily:'Inter', fontVariantNumeric:'tabular-nums', fontSize:16, fontWeight:600, color:s.color }}>{s.value}</div>
          </div>
        ))}
      </div>
      <div style={{ display:'flex', gap:12, fontFamily:'Inter', fontSize:12, color:'rgb(163,163,163)', margin:'10px 0 4px' }}>
        <span style={{ display:'flex', alignItems:'center', gap:6 }}><span style={{ width:8, height:8, borderRadius:2, background:'rgb(5,122,85)' }} /> Inflow</span>
        <span style={{ display:'flex', alignItems:'center', gap:6 }}><span style={{ width:8, height:8, borderRadius:2, background:'rgb(220,38,38)' }} /> Outflow</span>
      </div>
      <div style={{ flex:1, minHeight:200 }}>
        <HC options={opts} />
      </div>
    </Tile>
  );
}

/* 10. Projected Fees (long-term projection) ------------------------------ */
function ProjectedFees({ onMore }) {
  const years = ['2025','2026','2027','2028','2029','2030'];
  const base    = [150, 185, 235, 285, 340, 400];
  const opts = React.useMemo(() => ({
    chart: { type:'area', spacing:[10, 8, 4, 4] },
    xAxis: {
      categories: years,
      tickLength: 0,
    },
    yAxis: {
      min: 100, max: 500, tickInterval: 100,
      labels: { formatter: function () { return '$' + this.value + 'K'; } },
    },
    tooltip: { shared: true, valuePrefix: '$', valueSuffix: 'K' },
    legend: { enabled: false },
    plotOptions: {
      area: {
        fillColor: {
          linearGradient: { x1:0, y1:0, x2:0, y2:1 },
          stops: [[0, 'rgba(5,122,85,0.35)'], [1, 'rgba(5,122,85,0)']],
        },
        lineWidth: 2, color: 'rgb(5,122,85)',
        marker: { enabled: true, radius: 3, fillColor: 'rgb(10,10,10)', lineColor:'rgb(5,122,85)', lineWidth: 1.5 },
      },
    },
    series: [
      { type:'area', name:'Base', data: base },
    ],
  }), []);
  return (
    <Tile title="Projected Fees" onMore={onMore} footLabel="2025 – 2030 · Projection">
      <div style={{ flex:'0 0 80%', minHeight:0, height:'80%' }}>
        <HC options={opts} />
      </div>
    </Tile>
  );
}

/* 11. Holdings Breakdown — Top 10 holdings by AUM (matches details page) --- */
function Holdings({ onMore }) {
  const categories = ['VTSAX','BND','VTI','AGG','BCRED','VXUS','VOO','VEA','SPY','QQQ'];
  const data = [185,142,128,98,82,71,62,54,46,38];
  const opts = React.useMemo(() => ({
    chart: { type:'bar', height: 320, spacing:[8, 4, 8, 4], backgroundColor:'transparent' },
    xAxis: {
      categories,
      lineColor: 'rgba(75,85,99,0.4)',
      tickColor: 'transparent',
      labels: { style: { color: 'rgb(229,231,235)', fontFamily:'Inter', fontSize:'11.5px', fontWeight:'500' } },
    },
    yAxis: {
      min: 0,
      title: { text: null },
      gridLineColor: 'rgba(75,85,99,0.25)',
      gridLineDashStyle: 'Dash',
      labels: {
        style: { color: 'rgb(163,163,163)', fontFamily:'Inter', fontSize:'10.5px' },
        formatter: function () { return '$' + this.value + 'M'; },
      },
    },
    tooltip: { valuePrefix: '$', valueSuffix: 'M' },
    legend: { enabled: false },
    plotOptions: {
      bar: {
        borderRadius: 3,
        pointPadding: 0.08,
        groupPadding: 0.06,
        dataLabels: {
          enabled: true,
          align: 'left',
          inside: false,
          crop: false,
          overflow: 'allow',
          style: { color: 'rgb(249,250,251)', fontFamily:'Inter', fontWeight:'500', fontSize:'10.5px', textOutline:'none' },
          formatter: function () { return '$' + this.y + 'M'; },
        },
      },
    },
    series: [{
      name:'AUM',
      color:'rgba(5,122,85,0.45)',
      borderColor:'rgb(5,122,85)',
      borderWidth:1.5,
      data,
    }],
  }), []);
  return (
    <Tile title="Holdings Breakdown" onMore={onMore}>
      <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', padding:'0 0 6px' }}>Top 10 holdings by AUM</div>
      <div style={{ flex:1, minHeight:320 }}>
        <HC options={opts} />
      </div>
    </Tile>
  );
}

/* 12. Client Roster Heat (small rail) ----------------------------------- */
function ClientHeat({ onMore }) {
  const cols = 26, rows = 6;
  const cells = Array.from({length:cols*rows}, (_,i) => Math.random());
  const color = v => v<0.2 ? 'rgba(75,85,99,0.35)' : v<0.5 ? 'rgba(5,122,85,0.45)' : v<0.8 ? 'rgba(5,122,85,0.75)' : 'rgb(5,122,85)';
  return (
    <Tile title="Client Activity" onMore={onMore}>
      <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', padding:'0 0 6px' }}>Engagement, last 26 weeks</div>
      <div style={{ display:'grid', gridTemplateColumns:`repeat(${cols}, 1fr)`, gap:3, paddingBottom:6 }}>
        {cells.map((v,i) => (
          <div key={i} style={{ width:'100%', aspectRatio:'1', borderRadius:2, background:color(v) }} />
        ))}
      </div>
      <div style={{ display:'flex', alignItems:'center', gap:6, fontFamily:'Inter', fontSize:10.5, color:'rgb(163,163,163)', paddingTop:4 }}>
        Less
        <span style={{ width:10, height:10, borderRadius:2, background:'rgba(75,85,99,0.35)' }} />
        <span style={{ width:10, height:10, borderRadius:2, background:'rgba(5,122,85,0.45)' }} />
        <span style={{ width:10, height:10, borderRadius:2, background:'rgba(5,122,85,0.75)' }} />
        <span style={{ width:10, height:10, borderRadius:2, background:'rgb(5,122,85)' }} />
        More
      </div>
    </Tile>
  );
}

/* Insights tile — compact multi-provider summary for the main dashboard. */
function InsightsTile({ onMore }) {
  const rows = window.FIELD_INSIGHTS || [];
  const PM = window.INSIGHT_PROVIDER_META || {};
  const estK = (s) => { if (!s || s === '\u2014') return 0; const n = parseFloat(String(s).replace(/[^0-9.]/g,'')); return String(s).includes('M') ? n*1000 : n; };
  const total = rows.reduce((a,r)=>a+estK(r.est), 0);
  const totalLabel = total >= 1000 ? `$${(total/1000).toFixed(1)}M` : `$${Math.round(total)}K`;
  const clients = new Set(rows.map(r=>r.client)).size;
  const providers = new Set(rows.map(r=>r.provider)).size;
  const top = (() => { const l = [...rows].sort((a,b)=>estK(b.est)-estK(a.est)); const hi = l.findIndex(r=>r.provider==='Halo'); if (hi>0){ const [h]=l.splice(hi,1); l.unshift(h); } return l.slice(0,3); })();
  const openFlow = (id) => window.dispatchEvent(new CustomEvent('insight:open', { detail:{ id } }));
  const statCell = { padding:'14px 16px', borderRadius:10, border:'1px solid rgba(75,85,99,0.5)', background:'rgba(255,255,255,0.02)', cursor:'pointer' };
  const statNum = { fontFamily:'Inter', fontWeight:700, fontSize:22, color:'rgb(249,250,251)', fontVariantNumeric:'tabular-nums', letterSpacing:'-0.01em', lineHeight:1 };
  const statLbl = { fontFamily:'Inter', fontSize:11.5, color:'rgb(163,163,163)', marginTop:7, lineHeight:1.35 };
  const titleNode = (
    <span style={{ display:'inline-flex', alignItems:'center', gap:9 }}>
      <span style={{ width:24, height:24, borderRadius:6, background:'rgba(5,122,85,0.18)', border:'1px solid rgba(110,231,183,0.45)', display:'inline-flex', alignItems:'center', justifyContent:'center' }}>
        <i className="fa-solid fa-lightbulb" style={{ fontSize:12, color:'rgb(110,231,183)' }} />
      </span>
      <span>Insights</span>
    </span>
  );
  return (
    <Tile title={titleNode} onMore={onMore} footLabel={`${providers} providers`}>
      <div style={{ display:'flex', flexDirection:'column', gap:12 }}>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12 }}>
          <div onClick={onMore} style={statCell} onMouseEnter={e=>{e.currentTarget.style.borderColor='rgba(110,231,183,0.45)';}} onMouseLeave={e=>{e.currentTarget.style.borderColor='rgba(75,85,99,0.5)';}}>
            <div style={statNum}>{rows.length}</div>
            <div style={statLbl}>Open insights · {clients} clients</div>
          </div>
          <div onClick={onMore} style={statCell} onMouseEnter={e=>{e.currentTarget.style.borderColor='rgba(110,231,183,0.45)';}} onMouseLeave={e=>{e.currentTarget.style.borderColor='rgba(75,85,99,0.5)';}}>
            <div style={statNum}>{totalLabel}</div>
            <div style={statLbl}>Est. advisory impact</div>
          </div>
        </div>
        <div style={{ display:'flex', flexDirection:'column' }}>
          {top.map((r,i) => {
            const m = PM[r.provider] || {};
            return (
              <div key={r.id} onClick={()=>openFlow(r.id)} style={{ display:'grid', gridTemplateColumns:'26px 1fr auto', alignItems:'center', gap:11, padding:'10px 8px', margin:'0 -8px', borderTop:i?'1px solid rgba(75,85,99,0.45)':'none', cursor:'pointer', borderRadius:8, transition:'background 150ms ease' }}
                onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,0.03)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>
                <span style={{ width:26, height:26, borderRadius:6, background:m.brand||'rgb(40,40,40)', display:'inline-flex', alignItems:'center', justifyContent:'center', fontFamily:'Inter', fontWeight:800, fontSize:8.5, color:'#fff', border:'1px solid rgba(255,255,255,0.16)' }}>{m.abbr||''}</span>
                <div style={{ minWidth:0 }}>
                  <div style={{ fontFamily:'Inter', fontSize:13, fontWeight:500, color:'rgb(249,250,251)', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{r.client}</div>
                  <div style={{ fontFamily:'Inter', fontSize:11, color:'rgb(163,163,163)', marginTop:2 }}>{r.provider} · {r.type}</div>
                </div>
                <div style={{ fontFamily:'Inter', fontSize:12.5, fontWeight:600, color:'rgb(249,250,251)', fontVariantNumeric:'tabular-nums' }}>{r.est}</div>
              </div>
            );
          })}
        </div>
      </div>
    </Tile>
  );
}

Object.assign(window, {
  UpcomingMeetings, Notifications, Opportunities, TopClients,
  BillingSummary, ContentHub, AumAllocation, AumBars, CashFlow,
  ProjectedFees, Holdings, ClientHeat, TileInfo, InsightsTile, Tile,
});
